- name: shell run
  shell: 'psql -U postgres {{ db_name }} -c "DROP EXTENSION pgcrypto CASCADE;"'

- name: Install pip
  apt:
    update_cache: yes
    name:
    - python3-pip
  become: true
  
- name: Install pexpect
  pip:
    name: pexpect
  become: true
  
- name: clean db
  expect:
    command: '{{ dspace_install_dir }}/bin/dspace database clean' 
    responses:
      y/n: 'y'
    echo: yes
    timeout: 30  

- name: update db
  shell: 'psql -U postgres {{ db_name }} < {{ migrate_path }}' 

- name: update db
  shell: '{{ dspace_install_dir }}/bin/dspace database migrate ignored' 

# - name: Add pgcrypto
#   community.postgresql.postgresql_ext:
#     name: pgcrypto
#     db: '{{ db_name }}'
#     state: present
#     login_user: "{{ postgres_user }}"
#     login_password: "{{ postgres_password }}"
#   become: true   

- name: restart tomcat
  shell: systemctl restart tomcat9
  become: true  

- name: Create dspace user
  shell: '{{ dspace_install_dir }}/bin/dspace create-administrator -e {{ admin_email }} -f {{ admin_first_name }} -l {{ admin_last_name }} -p {{ admin_password }} -c en'
  
- name: Create dspace users
  shell: '{{ dspace_install_dir }}/bin/dspace create-administrator -e {{ item.email }} -f {{ item.first_name }} -l {{ item.last_name }} -p {{ item.password }} -c en'
  with_items:
    - "{{ dspace_users }}" 
