- name: shell run
  shell: 'psql -U postgres {{ db_name }} -c "DROP EXTENSION pgcrypto CASCADE;"'
  become: true

- name: Install pip
  apt:
    update_cache: yes
    name:
    - python3-pip
  become: true
  
- name: Install pexpect
  pip:
    name: pexpect
  become: true
  
- name: clean db
  expect:
    command: '{{ dspace_install_dir }}/bin/dspace database clean' 
    responses:
      y/n: 'y'
    echo: yes
    timeout: 30  
  become: true 

- name: update db
  shell: 'psql -U postgres {{ db_name }} < {{ migrate_path }}' 
  become: true  

# - name: Add pgcrypto
#   community.postgresql.postgresql_ext:
#     name: pgcrypto
#     db: '{{ db_name }}'
#     state: present
#     login_user: "{{ postgres_user }}"
#     login_password: "{{ postgres_password }}"
#   become: true   

- name: restart tomcat
  shell: systemctl restart tomcat9
  become: true  
